name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build
        shell: pwsh
        run: .\gradlew.bat clean build --stacktrace
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: feur_shadow_elytra
          path: |
            build\libs\*.jar
            !build\libs\*sources*.jar
            !build\libs\*javadoc*.jar

